angular.module("wordApp").factory("mockService", [function($timeout) {

    function getMockData() {
      let data = {
        nodes: [],
        edges: []
      };

      data.nodes = [
        {
          id: 1,
          label: "USA",
          value: 10,
          group: "word"
        }, {
          id: 2,
          label: 'wysłać',
          value: 10,
          group: "word"
        }, {
          id: 3,
          label: "sobota",
          value: 10,
          group: "word"
        }, {
          id: 4,
          label: "Singapur",
          value: 10,
          group: "word"
        }, {
          id: 5,
          label: "Korea",
          value: 15,
          group: "word"
        }, {
          id: 6,
          label: "Północny",
          value: 15,
          group: "word"
        }, {
          id: 9,
          label: "niszczyciel",
          value: 10,
          group: "word"
        }, {
          id: 10,
          label: "krążownik",
          value: 10,
          group: "word"
        }, {
          id: 11,
          label: "rakietowy",
          value: 10,
          group: "word"
        }, {
          id: 12,
          label: "środa",
          value: 10,
          group: "word"
        }, {
          id: 13,
          label: "kierunek",
          value: 10,
          group: "word"
        }, {
          id: 16,
          label: "ramy",
          value: 10,
          group: "word"
        }, {
          id: 17,
          label: "intensyfikacja",
          value: 10,
          group: "word"
        }, {
          id: 18,
          label: "swój",
          value: 10,
          group: "word"
        }, {
          id: 19,
          label: "program",
          value: 10,
          group: "word"
        }, {
          id: 20,
          label: "zbrojeniowy",
          value: 10,
          group: "word"
        }, {
          id: 21,
          label: "wystrzelić",
          value: 10,
          group: "word"
        }, {
          id: 22,
          label: "kolejny",
          value: 10,
          group: "word"
        }, {
          id: 23,
          label: "rakieta",
          value: 10,
          group: "word"
        }, {
          id: 24,
          label: "balistyczny",
          value: 10,
          group: "word"
        }, {
          id: 14,
          label: "lotniskowiec",
          value: 10,
          group: "word"
        }, {
          id: 28262,
          label: "28262",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 51768,
          label: "51768",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 54897,
          label: "54897",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 2715,
          label: "2715",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 60178,
          label: "60178",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 5092,
          label: "5092",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 414651,
          label: "414651",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 414655,
          label: "414655",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 230709,
          label: "230709",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 54265,
          label: "54256",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 1233,
          label: "1233",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 25648,
          label: "25648",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 54256,
          label: "54256",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 243704,
          label: "243704",
          shape: "circle",
          value: 15,
          group: "synset"
        }, {
          id: 8725,
          label: "8725",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 10141,
          label: "10141",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 398382,
          label: "398382",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 435379,
          label: "435379",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 13651,
          label: "13651",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 13671,
          label: "13671",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 23410,
          label: "23410",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 13646,
          label: "13646",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 48158,
          label: "48158",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 76556,
          label: "76556",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 235879,
          label: "235879",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 5093,
          label: "5093",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 230727,
          label: "230727",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 17096,
          label: "17096",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 80708,
          label: "80708",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 461363,
          label: "461363",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 398587,
          label: "398587",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 461569,
          label: "461569",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 10698,
          label: "10698",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 7292,
          label: "7292",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 7467,
          label: "7467",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 79995,
          label: "79995",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 244811,
          label: "244811",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 244812,
          label: "244812",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 3294,
          label: "3294",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 62096,
          label: "62096",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 62098,
          label: "62098",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 9166,
          label: "9166",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 420067,
          label: "420067",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 36483,
          label: "36483",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 7327,
          label: "7327",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 7328,
          label: "7328",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 51779,
          label: "51779",
          shape: "circle",
          value: 10,
          group: "synset"
        }, {
          id: 235754,
          label: "235754",
          shape: "circle",
          value: 10,
          group: "synset"
        }
      ];
      data.edges = [
        {
          from: 1,
          to: 28262,
          width: 10
        }, {
          from: 2,
          to: 51768,
          width: 3
        }, {
          from: 2,
          to: 54897,
          width: 2.6
        }, {
          from: 2,
          to: 2715,
          width: 2.5
        }, {
          from: 2,
          to: 60178,
          width: 1.9
        }, {
          from: 3,
          to: 5092,
          width: 4.6
        }, {
          from: 3,
          to: 414651,
          width: 2.7
        }, {
          from: 3,
          to: 414655,
          width: 2.7
        }, {
          from: 4,
          to: 230709,
          width: 10
        }, {
          from: 13,
          to: 54265,
          width: 2.7
        }, {
          from: 13,
          to: 1233,
          width: 2.5
        }, {
          from: 13,
          to: 25648,
          width: 1.9
        }, {
          from: 13,
          to: 54256,
          width: 1.5
        }, {
          from: 5,
          to: 243704,
          width: 10
        }, {
          from: 6,
          to: 8725,
          width: 2.6
        }, {
          from: 6,
          to: 10141,
          width: 1.5
        }, {
          from: 6,
          to: 398382,
          width: 1.2
        }, {
          from: 6,
          to: 435379,
          width: 1.2
        }, {
          from: 14,
          to: 13651,
          width: 10
        }, {
          from: 9,
          to: 13671,
          width: 5.2
        }, {
          from: 9,
          to: 23410,
          width: 4.8
        }, {
          from: 10,
          to: 13646,
          width: 6
        }, {
          from: 10,
          to: 48158,
          width: 4
        }, {
          from: 11,
          to: 76556,
          width: 5
        }, {
          from: 11,
          to: 235879,
          width: 5
        }, {
          from: 12,
          to: 5093,
          width: 10
        }, {
          from: 16,
          to: 230727,
          width: 10
        }, {
          from: 17,
          to: 17096,
          width: 5.2
        }, {
          from: 17,
          to: 80708,
          width: 4.8
        }, {
          from: 18,
          to: 461363,
          width: 4
        }, {
          from: 18,
          to: 398587,
          width: 3.3
        }, {
          from: 18,
          to: 461569,
          width: 2.6
        }, {
          from: 19,
          to: 10698,
          width: 1.5
        }, {
          from: 19,
          to: 7292,
          width: 1.2
        }, {
          from: 19,
          to: 7467,
          width: 1.2
        }, {
          from: 19,
          to: 79995,
          width: 1.1
        }, {
          from: 20,
          to: 244811,
          width: 5
        }, {
          from: 20,
          to: 244812,
          width: 5
        }, {
          from: 21,
          to: 3294,
          width: 3.7
        }, {
          from: 21,
          to: 62096,
          width: 3.3
        }, {
          from: 21,
          to: 62098,
          width: 3
        }, {
          from: 22,
          to: 9166,
          width: 5.2
        }, {
          from: 22,
          to: 420067,
          width: 4.8
        }, {
          from: 23,
          to: 36483,
          width: 2.8
        }, {
          from: 23,
          to: 7327,
          width: 2
        }, {
          from: 23,
          to: 7328,
          width: 1.5
        }, {
          from: 23,
          to: 51779,
          width: 1.4
        }, {
          from: 24,
          to: 235754,
          width: 10
        }, {
          from: 1,
          to: 2,
          width: 3,
          color: "red"
        }, {
          from: 2,
          to: 3,
          width: 3,
          color: "red"
        }, {
          from: 3,
          to: 4,
          width: 3,
          color: "red"
        }, {
          from: 4,
          to: 13,
          width: 3,
          color: "red"
        }, {
          from: 13,
          to: 5,
          width: 3,
          color: "red"
        }, {
          from: 5,
          to: 6,
          width: 3,
          color: "red"
        }, {
          from: 5,
          to: 6,
          width: 3,
          color: "#7aff28"
        }, {
          from: 6,
          to: 14,
          width: 3,
          color: "red"
        }, {
          from: 14,
          to: 9,
          width: 3,
          color: "red"
        }, {
          from: 9,
          to: 10,
          width: 3,
          color: "red"
        }, {
          from: 10,
          to: 11,
          width: 3,
          color: "red"
        }, {
          from: 12,
          to: 5,
          width: 3,
          color: "#7aff28"
        }, {
          from: 6,
          to: 16,
          width: 3,
          color: "#7aff28"
        }, {
          from: 16,
          to: 17,
          width: 3,
          color: "#7aff28"
        }, {
          from: 17,
          to: 18,
          width: 3,
          color: "#7aff28"
        }, {
          from: 18,
          to: 19,
          width: 3,
          color: "#7aff28"
        }, {
          from: 19,
          to: 20,
          width: 3,
          color: "#7aff28"
        }, {
          from: 20,
          to: 21,
          width: 3,
          color: "#7aff28"
        }, {
          from: 21,
          to: 22,
          width: 3,
          color: "#7aff28"
        }, {
          from: 22,
          to: 23,
          width: 3,
          color: "#7aff28"
        }, {
          from: 23,
          to: 24,
          width: 3,
          color: "#7aff28"
        }
      ];

      return data;
    }

    return {
      getMockData: getMockData
    }
  }
]);
